### ISSUE TITLE
Support pathlib.Path where file paths are expected

### ISSUE THREAD

**Issue by daniel-j-h** [osmcode/pyosmium#119]
Hey hey :wave: would be cool to support `pathlib.Path` when paths to files are expected, e.g. in `apply_file` (probably in other functions, too). Workaround right now: `str(Path("mypath"))`.

With a `pathlib.Path` we fail type checking right now:

```
Traceback (most recent call last):
  File "/usr/lib/python3.6/runpy.py", line 193, in _run_module_as_main
    "__main__", mod_spec)
  File "/usr/lib/python3.6/runpy.py", line 85, in _run_code
    exec(code, run_globals)
  File "/usr/src/app/danisahne/cli/__main__.py", line 92, in <module>
    main(parser.parse_args())
  File "/usr/src/app/danisahne/cli/__main__.py", line 80, in main
    handler.apply_file(args.map)
TypeError: apply_file(): incompatible function arguments. The following argument types are supported:
    1. (self: osmium._osmium.SimpleHandler, filename: str, locations: bool = False, idx: str = 'flex_mem') -> None
```

Not urgent, not blocking; just :cherries: on top of the :cake: :hugs:

**Comment by lonvia** [comment]
This is a Python3 only library. I'll leave this for after the next release when Python2 support gets dropped.
