### ISSUE TITLE
Fails to build with pybind11 2.6.0

### ISSUE THREAD

**Issue by sebastic** [osmcode/pyosmium#147]
The pybind11 package in Debian was recently updated to 2.6.0 which causes the pyosmium build to fail:
```
CMake Warning (dev) at /usr/lib/cmake/pybind11/pybind11Common.cmake:167 (if):
  Policy CMP0057 is not set: Support new IN_LIST if() operator.  Run "cmake
  --help-policy CMP0057" for policy details.  Use the cmake_policy command to
  set the policy and suppress this warning.

  IN_LIST will be interpreted as an operator when the policy is set to NEW.
  Since the policy is not set the OLD behavior will be used.
Call Stack (most recent call first):
  /usr/lib/cmake/pybind11/pybind11Config.cmake:249 (include)
  CMakeLists.txt:19 (find_package)
This warning is for project developers.  Use -Wno-dev to suppress it.

CMake Error at /usr/lib/cmake/pybind11/pybind11Common.cmake:167 (if):
  if given arguments:

    "11" "IN_LIST" "supported_standards"

  Unknown arguments specified
Call Stack (most recent call first):
  /usr/lib/cmake/pybind11/pybind11Config.cmake:249 (include)
  CMakeLists.txt:19 (find_package)


-- Configuring incomplete, errors occurred!
See also "/build/pyosmium-3.0.1/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeOutput.log".
See also "/build/pyosmium-3.0.1/build/temp.linux-x86_64-3.9/CMakeFiles/CMakeError.log".
Traceback (most recent call last):
  File "/build/pyosmium-3.0.1/setup.py", line 121, in <module>
    setup(
  File "/usr/lib/python3/dist-packages/setuptools/__init__.py", line 153, in setup
    return distutils.core.setup(**attrs)
  File "/usr/lib/python3.9/distutils/core.py", line 148, in setup
    dist.run_commands()
  File "/usr/lib/python3.9/distutils/dist.py", line 966, in run_commands
    self.run_command(cmd)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/usr/lib/python3.9/distutils/command/build.py", line 135, in run
    self.run_command(cmd_name)
  File "/usr/lib/python3.9/distutils/cmd.py", line 313, in run_command
    self.distribution.run_command(command)
  File "/usr/lib/python3.9/distutils/dist.py", line 985, in run_command
    cmd_obj.run()
  File "/build/pyosmium-3.0.1/setup.py", line 67, in run
    self.build_extension(ext)
  File "/build/pyosmium-3.0.1/setup.py", line 110, in build_extension
    subprocess.check_call(['cmake', ext.sourcedir] + cmake_args, cwd=self.build_temp, env=env)
  File "/usr/lib/python3.9/subprocess.py", line 373, in check_call
    raise CalledProcessError(retcode, cmd)
subprocess.CalledProcessError: Command '['cmake', '/build/pyosmium-3.0.1', '-DCMAKE_LIBRARY_OUTPUT_DIRECTORY=/build/pyosmium-3.0.1/.pybuild/cpython3_3.9_pyosmium/build', '-DPYTHON_EXECUTABLE=/usr/bin/python3.9', '-DCMAKE_BUILD_TYPE=Release']' returned non-zero exit status 1.
```

**Comment by sebastic** [comment]
The following patch fixes the issue:
```diff
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -8,9 +8,9 @@ include_directories(SYSTEM ${OSMIUM_INCL
 include_directories(${CMAKE_CURRENT_SOURCE_DIR}/lib)
 
 if(MSVC)
-    set(PYBIND11_CPP_STANDARD /std:c++14)
+    set(CMAKE_CXX_STANDARD 14)
 else()
-    set(PYBIND11_CPP_STANDARD -std=c++11)
+    set(CMAKE_CXX_STANDARD 11)
 endif()
 
 if(PYBIND11_PREFIX)
```
Per: https://github.com/pybind/pybind11/blob/v2.6.0/docs/upgrade.rst#cmake-support
> `PYBIND11_CPP_STANDARD=<platform-flag>` is deprecated, please use `CMAKE_CXX_STANDARD=<number>` instead, or any other valid CMake CXX or CUDA standard selection method, like `target_compile_features`.

**Comment by lonvia** [comment]
Thanks for tracking this down. I'll do a proper release with support for pybind11 2.6 in the next couple of days.

**Comment by lonvia** [comment]
I went for setting both PYBIND11_CPP_STANDARD and CMAKE_CXX_STANDARD to be backwards compatible with older pybind11 versions.

You can now also set CMAKE_CXX_STANDARD=14 via an environment variable for setup.py. Only 11 and 14 are known to work at the moment.
