### ISSUE TITLE
AttributeError: 'MallHandler' object has no attribute 'malls'

### ISSUE THREAD

**Issue by akvallapuram** [osmcode/pyosmium#161]
I am unsure why I am getting this error. 

```
python version: 3.8.5
osmium version: 3.1.0
```

Code:
```
#!/usr/bin/env python
# coding: utf-8


import json
import osmium
import pickle
from shapely.geometry import Polygon
import geopandas as gpd


# global GeoJSON factory
factory = osmium.geom.GeoJSONFactory()



class MallHandler(osmium.SimpleHandler):
    def __int__(self):
        osmium.SimpleHandler.__init__(self)
        self.malls = []
        
    def area(self, a):
        if a.tags.get('shop') == 'mall':
            mall_poly = factory.create_multipolygon(a)
            mall_json = json.loads(mall_poly)
            mall_shape = Polygon(mall_json['coordinates'][0][0])
            
            self.malls.append({
                'mall_id': a.id,
                'name': a.tags.get('name'),
                'geometry': mall_shape
            })


def extract_malls_from_country_map(country_map_file, country_mall_file):
    # extract malls
    mall_handler = MallHandler()
    mall_handler.apply_file(country_map_file, locations=True)
    
    # convert to GeoDataFrame and save results
    country_malls_gdf = gpd.GeoDataFrame(mall_handler.malls)
    
    print(f"# malls extracted from {country_map_file}: {len(country_malls_gdf)}")
    country_malls_gdf.to_file(country_mall_file)
    

# ## Main

# ### Turkey


extract_malls_from_country_map(
    "../data/maps/turkey-140101.osm.pbf",
    "../data/malls/turkey-140101.shp"
)
```

Output:
```
Traceback (most recent call last):
  File "country_mall_extraction_OSM.py", line 52, in <module>
    extract_malls_from_country_map(
  File "country_mall_extraction_OSM.py", line 38, in extract_malls_from_country_map
    mall_handler.apply_file(country_map_file, locations=True)
  File "country_mall_extraction_OSM.py", line 28, in area
    self.malls.append({
AttributeError: 'MallHandler' object has no attribute 'malls'
```

**Comment by lonvia** [comment]
It's a typo: `__int__` --> `__init__`.

**Comment by akvallapuram** [comment]
Silly of me. Thanks!
