### ISSUE TITLE
docs fail to build with setuptools >= 62.1.0

### ISSUE THREAD

**Issue by stratakis** [osmcode/pyosmium#205]
On doc/conf.py the directory for building the docs is defined as:
```
build_dir = "../build/lib.%s-%d.%d" % (
                    sysconfig.get_platform(),
                    sys.version_info[0], sys.version_info[1])
```

However since setuptools version 62.1.0 https://github.com/pypa/setuptools/pull/3258/commits/1c23f5e1e4b18b50081cbabb2dea22bf345f5894 that scheme changed and when before it would be for example `lib.linux-x86_64-3.9`, with the latest scheme it would be `lib.linux-x86_64-cpython39`, hence making the docs build to fail with:
```
+ cd doc
+ make html SPHINXBUILD=sphinx-build-3
sphinx-build-3 -b html -d _build/doctrees   . _build/html
Running Sphinx v4.5.0

        Compiled version of pyosmium not found, please build pyosmium
        for Python 3.11.
        Expected build directory: ../build/lib.linux-x86_64-3.11 

Configuration error:
There is a programmable error in your configuration file:

Traceback (most recent call last):
  File "/usr/lib/python3.11/site-packages/sphinx/config.py", line 332, in eval_config_file
    exec(code, namespace)
    ^^^^^^^^^^^^^^^^^^^^^
  File "/builddir/build/BUILD/pyosmium-3.3.0/doc/conf.py", line 33, in <module>
    from osmium.version import pyosmium_major, pyosmium_release
    ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
ModuleNotFoundError: No module named 'osmium'

make: *** [Makefile:53: html] Error 2
```

**Comment by lonvia** [comment]
Fixed in 7e68789678411101a40463a46430802a3966da52.
