### ISSUE TITLE
No module named _osmium

### ISSUE THREAD

**Issue by Xevib** [osmcode/pyosmium#31]
I installed pyosmium on Opensuse 42.2 and i'm geting this error:
>>> import osmium
Traceback (most recent call last):
  File "<stdin>", line 1, in <module>
  File "osmium/__init__.py", line 1, in <module>
    from osmium._osmium import *
ImportError: No module named _osmium

When I do `pip freeze|grep osmium` I get:
`osmium==2.12.0`

The python version is:
python --version
Python 2.7.12

The boost verion is 1.61

**Comment by Xevib** [comment]
Sorry the problem was that I was executing pytthon on the pysomium directory
