### ISSUE TITLE
Segmentation fault reading a osc fie

### ISSUE THREAD

**Issue by Xevib** [osmcode/pyosmium#32]
Withi this code:
```py
import osmium


class CounterHandler(osmium.SimpleHandler):
    def __init__(self):
        osmium.SimpleHandler.__init__(self)
        self.num_nodes = 0
        self.num_ways = 0
        self.num_rel = 0

    def changeset(self, c):
        print "change"
        self.count_hotel(c)

    def node(self, n):
        print 'node:{}'.format(self.num_nodes)
        self.num_nodes += 1

    def way(self, w):
        print 'way:{}'.format(self.num_ways)
        print w.id
        self.num_ways += 1

    def relation(self, r):
        print 'rel:{}'.format(self.num_rel)
        self.num_rel += 1

if __name__ == '__main__':
    h = CounterHandler()
    h.apply_file("781.osc.gz",osmium.osm.osm_entity_bits.CHANGESET)

    print("Number of nodes: %d" % h.num_nodes)
    print("Number of ways: %d" % h.num_ways)
    print("Number of rel: %d" % h.num_rel)

```
Where 781.osc.gz is:
http://planet.openstreetmap.org/replication/hour/000/039/781.osc.gz

I'm geting a segmentation fault,with a minute file it works.I also tried wiith the decompressed file and happens the same.

There is any way to know what is failing? There is no log with the segmentation fault

**Comment by lonvia** [comment]
I'm able to reproduce the segfault here. The relavant backtrace is:

```
#0  subitem_of_type<osmium::WayNodeList const, osmium::memory::CollectionIterator<osmium::memory::Item const> > (end=..., it=...) at ../libosmium/include/osmium/osm/entity.hpp:47
47                      if (TSubitem::is_compatible_to(it->type())) {
(gdb) bt
#0  subitem_of_type<osmium::WayNodeList const, osmium::memory::CollectionIterator<osmium::memory::Item const> > (end=..., it=...) at ../libosmium/include/osmium/osm/entity.hpp:47
#1  osmium::Way::nodes (this=this@entry=0x7fce03ba200f) at ../libosmium/include/osmium/osm/way.hpp:95
#2  0x00007fce0559ec8b in operator() (way=0x7fce03ba200f, sum=5, __closure=<synthetic pointer>)
    at ../libosmium/include/osmium/area/detail/segment_list.hpp:105
#3  accumulate<__gnu_cxx::__normal_iterator<const osmium::Way* const*, std::vector<const osmium::Way*> >, long unsigned int, osmium::area::detail::SegmentList::get_num_segments(const std::vector<const osmium::Way*>&)::<lambda(size_t, const osmium::Way*)> > (__binary_op=..., __init=5, __last=..., 
    __first=) at /usr/include/c++/4.9/bits/stl_numeric.h:154
#4  get_num_segments (members=std::vector of length 3, capacity 4 = {...})
    at ../libosmium/include/osmium/area/detail/segment_list.hpp:110
#5  extract_segments_from_ways (members=std::vector of length 3, capacity 4 = {...}, relation=..., 
    duplicate_nodes=@0x7ffc982edf60: 0, problem_reporter=0x0, this=0x7ffc982edee8)
    at ../libosmium/include/osmium/area/detail/segment_list.hpp:238
#6  osmium::area::Assembler::operator() (this=this@entry=0x7ffc982edee0, relation=..., 
    members=std::vector of length 3, capacity 4 = {...}, out_buffer=...)
    at ../libosmium/include/osmium/area/assembler.hpp:339
#7  0x00007fce055a39f3 in osmium::area::MultipolygonCollector<osmium::area::Assembler>::complete_relation (this=this@entry=0x7ffc982ee290, relation_meta=...)
    at ../libosmium/include/osmium/area/multipolygon_collector.hpp:186
#8  0x00007fce055a3e0a in osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::find_and_add_object (this=0x7ffc982ee290, object=...)
    at ../libosmium/include/osmium/relations/collector.hpp:407
#9  0x00007fce055a44c8 in way (way=
    {void (const osmium::Way &, osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::HandlerPass2 * const)} 0x7fce055a44b8 <BaseHandler::apply_with_area(osmium::io::Reader&, osmium::area::MultipolygonCollector<osmium::area::Assembler>&, std::string const&)+856>, this=0x7ffc982ee290) at ../libosmium/include/osmium/relations/collector.hpp:145
#10 apply_item_impl<osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::HandlerPass2&, osmium::memory::Item> (handler=..., item=...)
    at ../libosmium/include/osmium/visitor.hpp:64
#11 apply_item<osmium::memory::Item, osmium::handler::NodeLocationsForWays<osmium::index::map::Map<unsigned long, osmium::Location>, osmium::index::map::Dummy<unsigned long, osmium::Location> >&, BaseHandler&, osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::HandlerPass2&> (item=...) at ../libosmium/include/osmium/visitor.hpp:206
#12 apply<osmium::io::InputIterator<osmium::io::Reader>, osmium::handler::NodeLocationsForWays<osmium::index::map::Map<unsigned long, osmium::Location>, osmium::index::map::Dummy<unsigned long, osmium::Location> >&, BaseHandler&, osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::HandlerPass2&> (end=..., it=...)
    at ../libosmium/include/osmium/visitor.hpp:220
#13 apply<osmium::io::Reader, osmium::handler::NodeLocationsForWays<osmium::index::map::Map<unsigned long, osmium::Location>, osmium::index::map::Dummy<unsigned long, osmium::Location> >&, BaseHandler&, osmium::relations::Collector<osmium::area::MultipolygonCollector<osmium::area::Assembler>, false, true, false>::HandlerPass2&> (c=...) at ../libosmium/include/osmium/visitor.hpp:227
#14 BaseHandler::apply_with_area (this=this@entry=0x10e9180, r=..., collector=..., 
    idx="sparse_mem_array") at lib/generic_handler.hpp:59
```

The odd part here is that the segfault happens in the area handler which should never be called for your program. So there's two separate bugs here.

**Comment by lonvia** [comment]
6982500 fixes the issue where the area handler is called despite the fact there is no callback defined.

The most recent master version of libosmium also contains a fix for the segfault. It happened because the area handler was called on a file that may contain multiple versions of the same file (change files can contain multiple changes of the same file and need to be simplified first before using them with area or location handler).

Thanks again for the report.
