### ISSUE TITLE
Example use of create_linestring

### ISSUE THREAD

**Issue by snorfalorpagus** [osmcode/pyosmium#4]
The [amenity_list.py](https://github.com/osmcode/pyosmium/blob/master/examples/amenity_list.py) example only demonstrates how to create shapely geometries from areas. I've managed to get it working for points also, but trying to use `create_linestring` to create a linestring from a way raises an error:

```
Traceback (most recent call last):
  File "s_osm.py", line 30, in <module>
    h.apply_file(sys.argv[1], locations=True)
  File "s_osm.py", line 20, in way
    wkb = wkbfab.create_linestring(way)
Boost.Python.ArgumentError: Python argument types in
    WKBFactory.create_linestring(WKBFactory, Way)
did not match C++ signature:
    create_linestring(WKBFactory {lvalue} self, osmium::Way way, osmium::geom::use_nodes use_nodes='unique', osmium::geom::direction direction='forward')
    create_linestring(WKBFactory {lvalue} self, osmium::WayNodeList list, osmium::geom::use_nodes use_nodes='unique', osmium::geom::direction direction='forward')
```
I'm not familiar with python.boost, so I'm not sure if I'm calling this incorrectly, or if this is a bug.

Example code below:
```
import sys
import osmium
import shapely.speedups
if shapely.speedups.available:
    shapely.speedups.enable()
from shapely.wkb import loads

wkbfab = osmium.geom.WKBFactory()

class SHandler(osmium.SimpleHandler):
    def node(self, node):
        wkb = wkbfab.create_point(node)
        point = loads(wkb, hex=True)
    
    def way(self, way):
        wkb = wkbfab.create_linestring(way)
    
    def area(self, area):
        wkb = wkbfab.create_multipolygon(area)
        poly = loads(wkb, hex=True)
        centroid = poly.representative_point()

h = SHandler()
h.apply_file(sys.argv[1], locations=True)

```

**Comment by lonvia** [comment]
The additional parameters of `create_linestring()` had been exported with the wrong type. Your example should work now. You can also find a sample use of `WKBFactory.create_linestring()` in the newly added `test/test_geom.py`.
