### ISSUE TITLE
Cannot find boost_python library (boost(-python) 1.67 on macOS)

### ISSUE THREAD

**Issue by kkdd** [osmcode/pyosmium#57]
Hello,
```pip3 install osmium``` fails with printing an error ```Cannot find boost_python library```.
It worked when using boost(-python) 1.66.

```
$ uname
Darwin
$ sw_vers
ProductName:	Mac OS X
ProductVersion:	10.13.4
BuildVersion:	17E199
$ python3
Python 3.6.5 (default, Mar 30 2018, 06:41:53) 
[GCC 4.2.1 Compatible Apple LLVM 9.0.0 (clang-900.0.39.2)] on darwin
$ brew update boost-python3
$ brew info boost-python3
boost-python3: stable 1.67.0 (bottled), HEAD
C++ library for C++/Python3 interoperability
https://www.boost.org/
/usr/local/Cellar/boost-python3/1.67.0 (459 files, 17.5MB) *
  Poured from bottle on 2018-04-17 at 20:50:33
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/boost-python3.rb
==> Dependencies
Required: boost ✔, python ✔
==> Options
--HEAD
	Install HEAD version
$ 
$ pip3 install osmium
Collecting osmium
  Downloading https://files.pythonhosted.org/packages/72/41/a583e62ef20bbc1e5cd2afdf73c5af45de68e9e3914c9b5df927073bcf8c/osmium-2.14.0.tar.gz (1.6MB)
    100% |████████████████████████████████| 1.6MB 1.1MB/s 
    Complete output from command python setup.py egg_info:
    Traceback (most recent call last):
      File "<string>", line 1, in <module>
      File "/private/var/folders/q9/8661tgm10011b47nz9r52r180000gn/T/pip-install-c1mlbh1c/osmium/setup.py", line 78, in <module>
        raise Exception("Cannot find boost_python library")
    Exception: Cannot find boost_python library
    
    ----------------------------------------
Command "python setup.py egg_info" failed with error code 1 in /private/var/folders/q9/8661tgm10011b47nz9r52r180000gn/T/pip-install-c1mlbh1c/osmium/
```

**Comment by kkdd** [comment]
The building succeed by using ```boost_python36``` (= usr/local/lib/libboost_python36.dylib) and  ```/usr/local/Cellar/libosmium/2.14.0/libexec/include``` for protozero:

```
$ diff -u setup.py.orig setup.py
--- setup.py.orig
+++ setup.py
@@ -60,6 +60,7 @@
              "-py%d%d" % (pyversion.major, pyversion.minor),
              # Gentoo naming convention for version installed in parallel
              "-%d.%d" % (pyversion.major, pyversion.minor),
+             "%d%d" % (pyversion.major, pyversion.minor),
              # standard suffix for Python3
              "%d" % (pyversion.major),
              # standard naming
@@ -68,9 +69,10 @@
              "-mt"
            ]
 for suf in suffixes:
-    lib = find_library("boost_python%s" % suf)
-    if lib is not None:
-        libs.append("boost_python%s" % suf)
+    libboost = "boost_python%s" % suf
+    found = find_library(libboost)
+    if found:
+        libs.append(libboost)
         break
 else:
     # Visual C++ supports auto-linking, no library needed
@@ -120,6 +122,8 @@
         print("protozero found in '%s'" % prefix)
         includes.insert(0, os.path.join(prefix, 'include'))
 
+includes.insert(0, '/usr/local/Cellar/libosmium/2.14.0/libexec/include')
+
 if osplatform == "win32" :
     osmium_libs = ('expat', 'zlib', 'bzip2', 'ws2_32')
     extra_compile_args = [ '-DWIN32_LEAN_AND_MEAN', '-D_CRT_SECURE_NO_WARNINGS', '-DNOMINMAX', '/wd4996', '/EHsc' ]
$
$ brew install libosmium --with-google-sparsehash
$ brew info libosmium
libosmium: stable 2.14.0 (bottled)
Fast and flexible C++ library for working with OpenStreetMap data
http://osmcode.org/libosmium/
/usr/local/Cellar/libosmium/2.14.0 (219 files, 1.7MB) *
  Built from source on 2018-04-18 at 16:51:55 with: --with-google-sparsehash
From: https://github.com/Homebrew/homebrew-core/blob/master/Formula/libosmium.rb
==> Dependencies
Build: cmake ✔, boost ✔
Optional: google-sparsehash ✔, expat ✘, gdal ✘, proj ✔, doxygen ✘
==> Options
--with-doxygen
	Build with doxygen support
--with-expat
	Build with expat support
--with-gdal
	Build with gdal support
--with-google-sparsehash
	Build with google-sparsehash support
--with-proj
	Build with proj support
$ 
$ python3 setup.py build
Using global libosmium.
running build
running build_py
creating build
creating build/lib.macosx-10.13-x86_64-3.6
creating build/lib.macosx-10.13-x86_64-3.6/osmium
copying src/osmium/version.py -> build/lib.macosx-10.13-x86_64-3.6/osmium
copying src/osmium/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/osmium
creating build/lib.macosx-10.13-x86_64-3.6/osmium/osm
copying src/osmium/osm/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/osmium/osm
copying src/osmium/osm/mutable.py -> build/lib.macosx-10.13-x86_64-3.6/osmium/osm
creating build/lib.macosx-10.13-x86_64-3.6/osmium/replication
copying src/osmium/replication/server.py -> build/lib.macosx-10.13-x86_64-3.6/osmium/replication
copying src/osmium/replication/__init__.py -> build/lib.macosx-10.13-x86_64-3.6/osmium/replication
copying src/osmium/replication/utils.py -> build/lib.macosx-10.13-x86_64-3.6/osmium/replication
running build_ext
building 'osmium._osmium' extension
creating build/temp.macosx-10.13-x86_64-3.6
creating build/temp.macosx-10.13-x86_64-3.6/lib
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/osmium.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/osmium.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
In file included from lib/osmium.cc:8:
lib/generic_handler.hpp:114:10: warning: 'way' overrides a member function but
      is not marked 'override' [-Winconsistent-missing-override]
    void way(const osmium::Way& way) {
         ^
lib/generic_handler.hpp:31:14: note: overridden virtual function is here
virtual void way(const osmium::Way&) = 0;
             ^
lib/generic_handler.hpp:122:10: warning: 'relation' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
    void relation(const osmium::Relation& rel) {
         ^
lib/generic_handler.hpp:32:14: note: overridden virtual function is here
virtual void relation(const osmium::Relation&) = 0;
             ^
lib/generic_handler.hpp:130:10: warning: 'changeset' overrides a member function
      but is not marked 'override' [-Winconsistent-missing-override]
    void changeset(const osmium::Changeset& cs) {
         ^
lib/generic_handler.hpp:33:14: note: overridden virtual function is here
virtual void changeset(const osmium::Changeset&) = 0;
             ^
lib/generic_handler.hpp:138:10: warning: 'area' overrides a member function but
      is not marked 'override' [-Winconsistent-missing-override]
    void area(const osmium::Area& area) {
         ^
lib/generic_handler.hpp:34:14: note: overridden virtual function is here
virtual void area(const osmium::Area&) = 0;
             ^
4 warnings generated.
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/osmium.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/_osmium.cpython-36m-darwin.so
building 'osmium.io' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/io.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/io.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/io.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/io.cpython-36m-darwin.so
building 'osmium.index' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/index.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/index.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/index.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/index.cpython-36m-darwin.so
building 'osmium.geom' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/geom.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/geom.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/geom.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/geom.cpython-36m-darwin.so
building 'osmium.osm._osm' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/osm.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/osm.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/osm.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/osm/_osm.cpython-36m-darwin.so
building 'osmium.replication._replication' extension
clang++ -Wno-unused-result -Wsign-compare -Wunreachable-code -fno-common -dynamic -DNDEBUG -g -fwrapv -O3 -Wall -I/usr/local/Cellar/libosmium/2.14.0/libexec/include -I/usr/include -I/usr/local/include -I/usr/local/opt/openssl/include -I/usr/local/opt/sqlite/include -I/usr/local/Cellar/python/3.6.5/Frameworks/Python.framework/Versions/3.6/include/python3.6m -c lib/replication.cc -o build/temp.macosx-10.13-x86_64-3.6/lib/replication.o -std=c++11 -D_LARGEFILE_SOURCE -D_FILE_OFFSET_BITS=64 -D__STDC_FORMAT_MACROS
clang++ -bundle -undefined dynamic_lookup build/temp.macosx-10.13-x86_64-3.6/lib/replication.o -L/usr/lib -L/usr/local/lib -L/usr/local/opt/openssl/lib -L/usr/local/opt/sqlite/lib -lboost_python36 -lexpat -lpthread -lz -lbz2 -o build/lib.macosx-10.13-x86_64-3.6/osmium/replication/_replication.cpython-36m-darwin.so
running build_scripts
creating build/scripts-3.6
copying and adjusting tools/pyosmium-get-changes -> build/scripts-3.6
copying and adjusting tools/pyosmium-up-to-date -> build/scripts-3.6
changing mode of build/scripts-3.6/pyosmium-get-changes from 644 to 755
changing mode of build/scripts-3.6/pyosmium-up-to-date from 644 to 755
$ 
$ cd test
$ python3 run_tests.py 
..........................................................
----------------------------------------------------------------------
Ran 58 tests in 0.297s

OK
$
```

**Comment by lonvia** [comment]
I have merged your PR, thank you for that. Would you mind verifying that pip installation now works on your system? Build a source package with `python3 setup.py sdist` and then install it (preferably in a virtual env) with `pip3 install dist/osmium-2.14.0.tar.gz`.

**Comment by kkdd** [comment]
Thank you. I have confirmed that it works:

```
$ git clone https://github.com/osmcode/pyosmium.git
$ cd pyosmium
$ python3 setup.py sdist
Using global libosmium.
running sdist
running egg_info
writing src/osmium.egg-info/PKG-INFO
writing dependency_links to src/osmium.egg-info/dependency_links.txt
writing top-level names to src/osmium.egg-info/top_level.txt
reading manifest file 'src/osmium.egg-info/SOURCES.txt'
reading manifest template 'MANIFEST.in'
writing manifest file 'src/osmium.egg-info/SOURCES.txt'
running check
creating osmium-2.14.0
creating osmium-2.14.0/doc
creating osmium-2.14.0/examples
creating osmium-2.14.0/lib
creating osmium-2.14.0/src
creating osmium-2.14.0/src/osmium
creating osmium-2.14.0/src/osmium.egg-info
creating osmium-2.14.0/src/osmium/osm
creating osmium-2.14.0/src/osmium/replication
creating osmium-2.14.0/test
creating osmium-2.14.0/tools
copying files to osmium-2.14.0...
copying CHANGELOG.md -> osmium-2.14.0
copying LICENSE.TXT -> osmium-2.14.0
copying MANIFEST.in -> osmium-2.14.0
copying README.md -> osmium-2.14.0
copying README.rst -> osmium-2.14.0
copying setup.py -> osmium-2.14.0
copying doc/index.rst -> osmium-2.14.0/doc
copying doc/intro.rst -> osmium-2.14.0/doc
copying doc/ref_geom.rst -> osmium-2.14.0/doc
copying doc/ref_index.rst -> osmium-2.14.0/doc
copying doc/ref_io.rst -> osmium-2.14.0/doc
copying doc/ref_osm.rst -> osmium-2.14.0/doc
copying doc/ref_osmium.rst -> osmium-2.14.0/doc
copying doc/ref_replication.rst -> osmium-2.14.0/doc
copying doc/reference.rst -> osmium-2.14.0/doc
copying doc/tools.rst -> osmium-2.14.0/doc
copying doc/tools_get_changes.rst -> osmium-2.14.0/doc
copying doc/tools_uptodate.rst -> osmium-2.14.0/doc
copying examples/amenity_list.py -> osmium-2.14.0/examples
copying examples/convert.py -> osmium-2.14.0/examples
copying examples/create_nodecache.py -> osmium-2.14.0/examples
copying examples/filter_coastlines.py -> osmium-2.14.0/examples
copying examples/normalize_boolean.py -> osmium-2.14.0/examples
copying examples/osm_diff_stats.py -> osmium-2.14.0/examples
copying examples/osm_file_stats.py -> osmium-2.14.0/examples
copying examples/osm_replication_stats.py -> osmium-2.14.0/examples
copying examples/osm_url_stats.py -> osmium-2.14.0/examples
copying examples/pub_names.py -> osmium-2.14.0/examples
copying examples/road_length.py -> osmium-2.14.0/examples
copying examples/use_nodecache.py -> osmium-2.14.0/examples
copying lib/generic_handler.hpp -> osmium-2.14.0/lib
copying lib/generic_writer.hpp -> osmium-2.14.0/lib
copying lib/geom.cc -> osmium-2.14.0/lib
copying lib/index.cc -> osmium-2.14.0/lib
copying lib/io.cc -> osmium-2.14.0/lib
copying lib/merged_input.hpp -> osmium-2.14.0/lib
copying lib/osm.cc -> osmium-2.14.0/lib
copying lib/osmium.cc -> osmium-2.14.0/lib
copying lib/replication.cc -> osmium-2.14.0/lib
copying lib/std_pair.hpp -> osmium-2.14.0/lib
copying lib/win_boost_fix.hpp -> osmium-2.14.0/lib
copying lib/write_handler.hpp -> osmium-2.14.0/lib
copying src/osmium/__init__.py -> osmium-2.14.0/src/osmium
copying src/osmium/version.py -> osmium-2.14.0/src/osmium
copying src/osmium.egg-info/PKG-INFO -> osmium-2.14.0/src/osmium.egg-info
copying src/osmium.egg-info/SOURCES.txt -> osmium-2.14.0/src/osmium.egg-info
copying src/osmium.egg-info/dependency_links.txt -> osmium-2.14.0/src/osmium.egg-info
copying src/osmium.egg-info/top_level.txt -> osmium-2.14.0/src/osmium.egg-info
copying src/osmium/osm/__init__.py -> osmium-2.14.0/src/osmium/osm
copying src/osmium/osm/mutable.py -> osmium-2.14.0/src/osmium/osm
copying src/osmium/replication/__init__.py -> osmium-2.14.0/src/osmium/replication
copying src/osmium/replication/server.py -> osmium-2.14.0/src/osmium/replication
copying src/osmium/replication/utils.py -> osmium-2.14.0/src/osmium/replication
copying test/helpers.py -> osmium-2.14.0/test
copying test/run_tests.py -> osmium-2.14.0/test
copying test/test_geom.py -> osmium-2.14.0/test
copying test/test_index.py -> osmium-2.14.0/test
copying test/test_io.py -> osmium-2.14.0/test
copying test/test_memberlist.py -> osmium-2.14.0/test
copying test/test_nodelist.py -> osmium-2.14.0/test
copying test/test_osm.py -> osmium-2.14.0/test
copying test/test_replication.py -> osmium-2.14.0/test
copying test/test_taglist.py -> osmium-2.14.0/test
copying test/test_writer.py -> osmium-2.14.0/test
copying tools/pyosmium-get-changes -> osmium-2.14.0/tools
copying tools/pyosmium-up-to-date -> osmium-2.14.0/tools
Writing osmium-2.14.0/setup.cfg
Downloading and adding libosmium sources from https://github.com/osmcode/libosmium/archive/v2.14.0.tar.gz
Downloading and adding protozero sources from https://github.com/mapbox/protozero/archive/v1.6.2.tar.gz
creating dist
Creating tar archive
removing 'osmium-2.14.0' (and everything under it)
$
$ pip3 install dist/osmium-2.14.0.tar.gz 
Processing ./dist/osmium-2.14.0.tar.gz
Building wheels for collected packages: osmium
  Running setup.py bdist_wheel for osmium ... done
  Stored in directory: /Users/kkdd/Library/Caches/pip/wheels/b8/58/eb/7e80dc771ccc84c42a664d2044569a2410c1cb63481b71d4ae
Successfully built osmium
Installing collected packages: osmium
Successfully installed osmium-2.14.0
$
$ python3 -c "import osmium"
$ 
$ pip3 search osmium
osmium (2.14.0)  - Python bindings for libosmium, the data processing library for OSM data
  INSTALLED: 2.14.0 (latest)
$ 
```

**Comment by lonvia** [comment]
I've just uploaded the new version to PyPI.

**Comment by kkdd** [comment]
Thank you.
