### ISSUE TITLE
pyosmium-up-to-date; NameError: name 'extra_headers' is not defined

### ISSUE THREAD

**Issue by d3netxer** [osmcode/pyosmium#76]
(Also gave me a similar error using Python 2)
```
:~/osm_history_planet/pyosmium/tools$ python3 pyosmium-up-to-date -v -o ../../osm_history_w_applied_diffs.osm.pbf ../../history-180806.osm.pbf
2018-10-16 18:33:13,355 INFO: Using replication service at https://planet.osm.org/replication/hour/
2018-10-16 18:33:13,356 INFO: Using timestamp 2018-08-06 00:59:56+00:00 as starting point.
2018-10-16 18:33:15,131 INFO: Starting download at ID 51689 (max 1024 MB)
printing extra_headers
Traceback (most recent call last):
  File "pyosmium-up-to-date", line 228, in <module>
    ret = update_from_osm_server(ts, options)
  File "pyosmium-up-to-date", line 64, in update_from_osm_server
    None, ts, options)
  File "pyosmium-up-to-date", line 120, in update_from_custom_server
    print(extra_headers)
NameError: name 'extra_headers' is not defined
```

**Comment by lonvia** [comment]
Looks like your version of pyosmium-up-to-date and the pyosmium library don't match. Do you have an older version somewhere in your PYTHONPATH potentially installed with pip?

**Comment by d3netxer** [comment]
I'm not sure, when used ```pip install osmium``` it gave me the following:
```
~/osm_history_planet/pyosmium/tools$ pip install osmium
Collecting osmium
Installing collected packages: osmium
Successfully installed osmium-2.14.3
```

when tried to find the version number of osmium, I got the following:
```
osmium --version
osmium version 1.7.1
libosmium version 2.13.1
Copyright (C) 2013-2017  Jochen Topf <jochen@topf.org>
License: GNU GENERAL PUBLIC LICENSE Version 3 <https://gnu.org/licenses/gpl.html>.
This is free software: you are free to change and redistribute it.
There is NO WARRANTY, to the extent permitted by law.
```

I don't understand if these are the same osmiums or if different ones exist on my system.

**Comment by lonvia** [comment]
What does `which pyosmium-up-to-date` say? If you install pyosmium via pip, you need to use the binaries that come with it, which are usually installed in `/home/ubuntu/.local/bin`. You likely have also installed an older version of pyosmium via apt-get and are accidentally using that one.
