### ISSUE TITLE
Piping tag into another program gives "UnicodeEncodeError: 'ascii' codec can't encode characters in position 14-20: ordinal not in range(128)" on python2

### ISSUE THREAD

**Issue by ltog** [osmcode/pyosmium#94]
When I do the following call

    python encoding_issue2.py some-file.osm.pbf | grep foo

with the following source code:

```python
import osmium
import sys 

class DetailInfoHandler(osmium.SimpleHandler):

    def __init__(self):
        super(DetailInfoHandler, self).__init__()

    def print_obj_info(self, o): 
        for tag in o.tags:
            print(tag.k + " = " + tag.v)

    def node(self, n): 
        self.print_obj_info(n)

if __name__ == '__main__':
    if len(sys.argv) != 2:
        print("Usage: python encoding_issue2.py <osmfile>")
        sys.exit(-1)

    DetailInfoHandler().apply_file(sys.argv[1])
```

I get the following error:

```
Traceback (most recent call last):
  File "encoding_issue2.py", line 21, in <module>
    DetailInfoHandler().apply_file(sys.argv[1])
  File "encoding_issue2.py", line 14, in node
    self.print_obj_info(n)
  File "encoding_issue2.py", line 11, in print_obj_info
    print(tag.k + " = " + tag.v)
UnicodeEncodeError: 'ascii' codec can't encode characters in position 10-16: ordinal not in range(128)
```

The error happens only if I pipe the output into another program, otherwise the script works fine.

The issue might be related to #92 .

**Comment by lonvia** [comment]
FIxed with #92.
